const { contextBridge, ipcRenderer } = require('electron');

const api = {
  // accounts
  listAccounts:   ()      => ipcRenderer.invoke('accounts:list'),
  createAccount:  (data)  => ipcRenderer.invoke('accounts:create', data),
  updateAccount:  (data)  => ipcRenderer.invoke('accounts:update', data),
  deleteAccount:  (id)    => ipcRenderer.invoke('accounts:delete', id),
  reorderAccounts:(ids)   => ipcRenderer.invoke('accounts:reorder', ids),
  appVersion:     ()      => ipcRenderer.invoke('app:version'),
  installUpdate:  ()      => ipcRenderer.invoke('update:install'),
  onUpdateStatus: (cb)    => ipcRenderer.on('update-status', (_, data) => cb(data)),
  onDbError:          (cb) => ipcRenderer.on('db:error', (_, data) => cb(data)),
  clearTransferPair:  (d)  => ipcRenderer.invoke('tx:clear-transfer-pair', d),
  invMonthlyTotals:   (d)  => ipcRenderer.invoke('inv:monthly-totals', d),
  brokerMlLearn:      (d)  => ipcRenderer.invoke('broker:ml-learn', d),
  budgetList:         ()   => ipcRenderer.invoke('budget:list'),
  budgetSave:         (d)  => ipcRenderer.invoke('budget:save', d),
  budgetDelete:       (d)  => ipcRenderer.invoke('budget:delete', d),
  budgetActuals:      (d)  => ipcRenderer.invoke('budget:actuals', d),
  goalList:           ()   => ipcRenderer.invoke('goal:list'),
  goalSave:           (d)  => ipcRenderer.invoke('goal:save', d),
  goalDelete:         (d)  => ipcRenderer.invoke('goal:delete', d),
  goalAccountBalance: (d)  => ipcRenderer.invoke('goal:account-balance', d),
  goalAvgExpenses:    ()   => ipcRenderer.invoke('goal:avg-monthly-expenses'),
  goalAvgSavings:     ()   => ipcRenderer.invoke('goal:avg-monthly-savings'),
  settingsSetTourDone: ()  => ipcRenderer.invoke('settings:set-tour-done'),
  settingsSave:        (d) => ipcRenderer.invoke('settings:save-data', d),
  manualOpen:          (d) => ipcRenderer.invoke('manual:open', d),
  forgotPassword:      ()  => ipcRenderer.invoke('settings:forgot-password'),
  resetPassword:       (d) => ipcRenderer.invoke('settings:reset-password', d),
  hasRecoveryEmail:    ()  => ipcRenderer.invoke('settings:has-recovery-email'),
  fetchBCBSeries:      (d) => ipcRenderer.invoke('bcb:fetch-series', d),
  fetchBCBOlinda:      (d) => ipcRenderer.invoke('bcb:fetch-olinda', d),
  benchmarksSave:      (d) => ipcRenderer.invoke('benchmarks:save', d),
  benchmarksGet:       ()  => ipcRenderer.invoke('benchmarks:get'),
  benchmarksFetchAll:  ()  => ipcRenderer.invoke('benchmarks:fetch-all'),
  importDefaultsGet:  ()  => ipcRenderer.invoke('import-defaults:get'),
  importDefaultsSave: (d) => ipcRenderer.invoke('import-defaults:save', d),
  getBalance:        (id)    => ipcRenderer.invoke('accounts:balance', id),
  getBalanceBefore:  (opts)  => ipcRenderer.invoke('accounts:balance-before', opts),

  // transactions
  listTx:         (opts)  => ipcRenderer.invoke('tx:list', opts),
  createTx:       (tx)    => ipcRenderer.invoke('tx:create', tx),
  updateTx:       (tx)    => ipcRenderer.invoke('tx:update', tx),
  deleteTx:       (id)    => ipcRenderer.invoke('tx:delete', id),
  transfer:       (data)  => ipcRenderer.invoke('tx:transfer', data),
  importBatch:    (data)  => ipcRenderer.invoke('tx:import-batch', data),

  // QIF
  importQIF:      (data)  => ipcRenderer.invoke('qif:import', data),
  bankImport:     (data)  => ipcRenderer.invoke('bank:import', data),

  // reports
  reportSummary:  (opts)  => ipcRenderer.invoke('report:summary', opts),
  categoryDetail: (opts)  => ipcRenderer.invoke('report:category-detail', opts),
  reportSummaryHierarchical: (opts) => ipcRenderer.invoke('report:summary-hierarchical', opts),
  savedReportsList: ()     => ipcRenderer.invoke('saved-reports:list'),
  savedReportsSave: (r)    => ipcRenderer.invoke('saved-reports:save', r),
  overviewConfigGet:  ()   => ipcRenderer.invoke('overview-config:get'),
  overviewConfigSave: (c)  => ipcRenderer.invoke('overview-config:save', c),
  catTypesGet:    ()      => ipcRenderer.invoke('cat-types:get'),
  catTypesSave:   (d)     => ipcRenderer.invoke('cat-types:save', d),
  // Patrimônio
  patAssetsList:       ()    => ipcRenderer.invoke('pat:assets-list'),
  patAssetSave:        (d)   => ipcRenderer.invoke('pat:asset-save', d),
  patAssetDelete:      (d)   => ipcRenderer.invoke('pat:asset-delete', d),
  patFinancingGet:     (d)   => ipcRenderer.invoke('pat:financing-get', d),
  patFinancingSave:    (d)   => ipcRenderer.invoke('pat:financing-save', d),
  patFinancingPaidVal: (d)   => ipcRenderer.invoke('pat:financing-paid-value', d),
  patHistoryList:      (d)   => ipcRenderer.invoke('pat:history-list', d),
  patHistoryAll:       ()    => ipcRenderer.invoke('pat:history-all'),
  patHistorySet:       (d)   => ipcRenderer.invoke('pat:history-set', d),
  patAutoProject:      (d)   => ipcRenderer.invoke('pat:auto-project', d),
  patAccountsGet:      ()    => ipcRenderer.invoke('pat:accounts-get'),
  patAccountsSet:      (d)   => ipcRenderer.invoke('pat:accounts-set', d),
  patAccountBalances:  ()    => ipcRenderer.invoke('pat:account-balances'),
  patIpcaMonthlyFetch: ()    => ipcRenderer.invoke('pat:ipca-monthly-fetch'),
  patIpcaMonthlySave:  (d)   => ipcRenderer.invoke('pat:ipca-monthly-save', d),
  patIpcaMonthlyGet:   ()    => ipcRenderer.invoke('pat:ipca-monthly-get'),
  patImportHistory:    (d)   => ipcRenderer.invoke('pat:import-history', d),
  patImportHistoryFull:(d)   => ipcRenderer.invoke('pat:import-history-full', d),
  // Investimentos
  invAssetsList:       ()    => ipcRenderer.invoke('inv:assets-list'),
  invBrokersList:      ()    => ipcRenderer.invoke('inv:brokers-list'),
  invAssetSave:        (d)   => ipcRenderer.invoke('inv:asset-save', d),
  invAssetDelete:      (d)   => ipcRenderer.invoke('inv:asset-delete', d),
  invTxList:           (d)   => ipcRenderer.invoke('inv:tx-list', d),
  invTxAll:            ()    => ipcRenderer.invoke('inv:tx-all'),
  invTxSave:           (d)   => ipcRenderer.invoke('inv:tx-save', d),
  invTxReclassify:     (d)   => ipcRenderer.invoke('inv:tx-reclassify', d),
  invTxDelete:         (d)   => ipcRenderer.invoke('inv:tx-delete', d),
  invEnsurePurchase:   (d)   => ipcRenderer.invoke('inv:ensure-purchase', d),
  patHistoryDeleteManual:    (d) => ipcRenderer.invoke('pat:history-delete-manual', d),
  patHistoryClearManualSale: (d) => ipcRenderer.invoke('pat:history-clear-manual-sale', d),
  patTxList:   (d) => ipcRenderer.invoke('pat:tx-list', d),
  patTxSave:   (d) => ipcRenderer.invoke('pat:tx-save', d),
  patTxDelete: (d) => ipcRenderer.invoke('pat:tx-delete', d),
  patTxAll:    ()  => ipcRenderer.invoke('pat:tx-all'),
  showConfirm: (msg, detail) => ipcRenderer.invoke('dialog:confirm', { message: msg, detail }),
  patFinancingContractGet:  (d) => ipcRenderer.invoke('pat:financing-contract-get', d),
  patFinancingContractSave: (d) => ipcRenderer.invoke('pat:financing-contract-save', d),
  saveLang:    (lang) => ipcRenderer.invoke('settings:save', { language: lang }),
  licenseStatus:     ()            => ipcRenderer.invoke('license:status'),
  licenseActivate:   (code, email) => ipcRenderer.invoke('license:activate', { code, email }),
  licenseDeactivate: ()            => ipcRenderer.invoke('license:deactivate'),
  exportData:        ()            => ipcRenderer.invoke('export:data'),
  getSettings: ()     => ipcRenderer.invoke('settings:get'),
  patFinancingMarkPaid:     (d) => ipcRenderer.invoke('pat:financing-mark-paid', d),
  patFinancingUnpay:        (d) => ipcRenderer.invoke('pat:financing-unpay', d),
  financingFetchIndexes:    ()  => ipcRenderer.invoke('financing:fetch-indexes'),
  financingGetIndexes:      ()  => ipcRenderer.invoke('financing:get-indexes'),
  invBulkImportHistory:(d)   => ipcRenderer.invoke('inv:bulk-import-history', d),
  financialImport:     (d)   => ipcRenderer.invoke('financial:import', d),
  categoriesGet:       ()    => ipcRenderer.invoke('categories:get'),
  categoriesSave:      (d)   => ipcRenderer.invoke('categories:save', d),
  brokerMappingsGet:   ()    => ipcRenderer.invoke('broker:mappings-get'),
  brokerAccountPrefGet:(d)   => ipcRenderer.invoke('broker:account-pref-get', d),
  brokerAccountPrefSet:(d)   => ipcRenderer.invoke('broker:account-pref-set', d),
  brokerMappingLearn:  (d)   => ipcRenderer.invoke('broker:mapping-learn', d),
  brokerSaveParsed:    (d)   => ipcRenderer.invoke('broker:save-parsed', d),
  brokerCreateAdjustment:(d) => ipcRenderer.invoke('broker:create-adjustment', d),
  bankParsersList:     ()    => ipcRenderer.invoke('bank:parsers-list'),
  bankParserSave:      (d)   => ipcRenderer.invoke('bank:parser-save', d),
  bankParserDelete:    (d)   => ipcRenderer.invoke('bank:parser-delete', d),
  // Settings
  settingsGet:         ()    => ipcRenderer.invoke('settings:get'),
  settingsSetPassword: (d)   => ipcRenderer.invoke('settings:set-password', d),
  settingsSetDataDir:  ()    => ipcRenderer.invoke('settings:set-data-dir'),
  settingsClearDataDir:()    => ipcRenderer.invoke('settings:clear-data-dir'),
  // Login window handlers
  checkPassword:       (pw)  => ipcRenderer.invoke('login:check', pw),
  loginOk:             ()    => ipcRenderer.invoke('login:ok'),
  evolucaoIpcaGet:    ()   => ipcRenderer.invoke('evolucao:ipca-get'),
  evolucaoIpcaSave:   (d)  => ipcRenderer.invoke('evolucao:ipca-save', d),
  evolucaoIpcaFetch:  ()   => ipcRenderer.invoke('evolucao:ipca-fetch'),
  evolucaoSummary:    (o)  => ipcRenderer.invoke('evolucao:monthly-summary', o),
  evolucaoByCat:      (o)  => ipcRenderer.invoke('evolucao:monthly-by-category', o),
  reportMonthly:  (opts)  => ipcRenderer.invoke('report:monthly', opts),
  reportMonthlyByCategory: (opts) => ipcRenderer.invoke('report:monthly-by-category', opts),
  reportNetWorth: (opts)  => ipcRenderer.invoke('report:net-worth', opts),
  reportNetWorthHistory: () => ipcRenderer.invoke('report:net-worth-history'),
  reportBudget:   (opts)  => ipcRenderer.invoke('report:budget', opts),
  reportFuturePending: ()  => ipcRenderer.invoke('report:future-pending'),

  // ML
  mlPredict:      (data)  => ipcRenderer.invoke('ml:predict', data),
  mlLearn:        (data)  => ipcRenderer.invoke('ml:learn', data),
  mlList:         ()      => ipcRenderer.invoke('ml:list'),
  mlClear:        ()      => ipcRenderer.invoke('ml:clear'),
  mlExport:       ()      => ipcRenderer.invoke('ml:export'),
  mlImport:       (rules) => ipcRenderer.invoke('ml:import', rules),
  mlTrainHistory: ()      => ipcRenderer.invoke('ml:train-history'),

  // recurring
  listRecurring:   ()     => ipcRenderer.invoke('recurring:list'),
  createRecurring: (data) => ipcRenderer.invoke('recurring:create', data),
  deleteRecurring: (id)   => ipcRenderer.invoke('recurring:delete', id),
  updateRecurring: (data) => ipcRenderer.invoke('recurring:update', data),
  refreshRecurring:()     => ipcRenderer.invoke('recurring:refresh'),

  // dialogs
  openFile:       (opts)  => ipcRenderer.invoke('dialog:open-file', opts),
  saveFile:       (opts)  => ipcRenderer.invoke('dialog:save-file', opts),

  // backup
  backupNow:      ()      => ipcRenderer.invoke('backup:now'),
  backupList:     ()      => ipcRenderer.invoke('backup:list'),
  backupRestore:  (path)  => ipcRenderer.invoke('backup:restore', path),
  backupFolder:   ()      => ipcRenderer.invoke('backup:open-folder'),

  // undo
  undoPeek:       ()      => ipcRenderer.invoke('undo:peek'),
  undoApply:      ()      => ipcRenderer.invoke('undo:apply'),
  undoClear:      ()      => ipcRenderer.invoke('undo:clear'),

  // global search
  searchGlobal:   (opts)  => ipcRenderer.invoke('search:global', opts),

  // inline edit
  inlineUpdate:   (opts)  => ipcRenderer.invoke('tx:inline-update', opts),
};

contextBridge.exposeInMainWorld('ff', api);
